const API_BASE_URL = 'https://localhost:7297/api/';

const BASE_OPTIONS = {
  GET_DECK: 'cards',
  GET_GAME_ID: 'players/lastGame',
  GET_PLAYERS: 'players/',
  UPDATE_PLAYER: 'players/',
  POST_PLAYER: 'players'
}

const ENDPOINTS = {
  GET_DECK: API_BASE_URL + BASE_OPTIONS.GET_DECK,
  GET_GAME_ID: API_BASE_URL + BASE_OPTIONS.GET_GAME_ID,
  GET_PLAYERS: API_BASE_URL + BASE_OPTIONS.GET_PLAYERS,
  UPDATE_PLAYER: API_BASE_URL + BASE_OPTIONS.UPDATE_PLAYER,
  CREATE_PLAYER: API_BASE_URL + BASE_OPTIONS.POST_PLAYER
}

export default ENDPOINTS;
