// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project361.Data;

#nullable disable

namespace Project361.Data.Migrations;

[DbContext(typeof(PlayerContext))]
partial class PlayerContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

        modelBuilder.Entity("Project361.Models.Player", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("GameId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<int>("Score")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Players");

                b.HasData(
                    new
                    {
                        Id = 1,
                        GameId = 1,
                        Name = "Sam",
                        Score = 0
                    },
                    new
                    {
                        Id = 2,
                        GameId = 1,
                        Name = "Ethan",
                        Score = 0
                    },
                    new
                    {
                        Id = 3,
                        GameId = 1,
                        Name = "Aden",
                        Score = 0
                    },
                    new
                    {
                        Id = 4,
                        GameId = 1,
                        Name = "Pranav",
                        Score = 0
                    },
                    new
                    {
                        Id = 5,
                        GameId = 1,
                        Name = "Chris",
                        Score = 0
                    },
                    new
                    {
                        Id = 6,
                        GameId = 1,
                        Name = "Indigo",
                        Score = 0
                    });
            });
#pragma warning restore 612, 618
    }
}
